import {
  cadddr,
  caddr,
  cadr,
  Constants,
  istensor,
  issymbol,
  NIL,
  U,
} from '../runtime/defs';
import { stop } from '../runtime/run';
import { collectUserSymbols, get_printname, symbol } from '../runtime/symbol';
import { Eval } from './eval';
import {
  divides,
  fromMPoly,
  monic,
  MPoly,
  mpMulTerm,
  mpPrimitive,
  mpReduce,
  mpSub,
  Order,
  ORDERS,
  toMPoly,
} from './mpoly';
import { equationToExpr } from './roots';
import { build_tensor } from './scan';

/* groebner ===================================================================

Parameters
----------
polys,vars,order

General description
-------------------
Returns the reduced Groebner basis of the ideal generated by the list of
polynomials (or equations) polys with rational coefficients. vars lists the
variables, largest first (default: the symbols of polys); order is lex
(default), grlex or grevlex. Each basis polynomial has integer coefficients
without common factor and a positive leading coefficient.

  groebner([x*y-1,x-y],[x,y])
  > [x-y,y^2-1]

*/
export function Eval_groebner(p1: U) {
  // equations are converted before Eval, see Eval_solve
  const arg = cadr(p1);
  const single = istensor(arg) ? undefined : equationToExpr(arg);
  const polys = istensor(arg)
    ? arg.elem.map(equationToExpr)
    : istensor(single)
    ? single.elem
    : [single];

  let vars: U | U[] = Eval(caddr(p1));
  if (vars === symbol(NIL)) {
    vars = [];
    polys.forEach((p) => collectUserSymbols(p, vars as U[]));
  } else {
    vars = istensor(vars) ? vars.elem : [vars];
  }
  if (!vars.every(issymbol) || new Set(vars).size !== vars.length) {
    stop('groebner: variables must be distinct symbols');
  }

  const o = cadddr(p1) === symbol(NIL) ? symbol(NIL) : Eval(cadddr(p1));
  const name = o === symbol(NIL) ? 'lex' : issymbol(o) ? get_printname(o) : '';
  const ord = ORDERS.hasOwnProperty(name) ? ORDERS[name] : undefined;
  if (!ord) {
    stop('groebner: order must be lex, grlex or grevlex');
  }

  const G = groebner(
    polys.map((p) => toMPoly(p, vars as U[], ord)),
    ord
  );
  return build_tensor(
    G.length ? G.map((g) => fromMPoly(g, vars as U[])) : [Constants.zero]
  );
}

// Buchberger: add the reduced S-polynomial of every pair until all reduce
// to zero, then make the basis minimal and reduced.
// ponytail: plain Buchberger with the coprime criterion only; add the chain
// criterion / sugar strategy (or F4) if large systems matter.
export function groebner(F: MPoly[], ord: Order): MPoly[] {
  const G = F.filter((p) => p.length).map(monic);
  const pairs: [number, number][] = [];
  G.forEach((_, j) => {
    for (let i = 0; i < j; i++) pairs.push([i, j]);
  });
  while (pairs.length) {
    const [i, j] = pairs.shift();
    const [f, g] = [G[i], G[j]];
    const L = f[0].e.map((x, k) => Math.max(x, g[0].e[k]));
    // coprime leading monomials: the S-polynomial reduces to zero
    if (L.every((x, k) => x === f[0].e[k] + g[0].e[k])) continue;
    const s = mpSub(
      mpMulTerm(f, Constants.one, L.map((x, k) => x - f[0].e[k])),
      mpMulTerm(g, Constants.one, L.map((x, k) => x - g[0].e[k])),
      ord
    );
    const r = mpReduce(s, G, ord);
    if (r.length) {
      G.push(monic(r));
      for (let k = 0; k < G.length - 1; k++) pairs.push([k, G.length - 1]);
    }
  }

  // minimal: drop g when another leading monomial divides lt(g); of equal
  // leading monomials the first one stays
  const minimal = G.filter(
    (g, i) =>
      !G.some(
        (h, j) =>
          j !== i &&
          divides(h[0].e, g[0].e) &&
          (ord(h[0].e, g[0].e) !== 0 || j < i)
      )
  );
  // reduced: the leading terms stay, no other term is divisible by one
  return minimal
    .map((g) => [
      g[0],
      ...mpReduce(
        g.slice(1),
        minimal.filter((h) => h !== g),
        ord
      ),
    ])
    .sort((a, b) => ord(b[0].e, a[0].e))
    .map(mpPrimitive);
}
